services:
  postgres:
    image: postgres:18
    container_name: postgres
    environment:
      - POSTGRES_USER=postgres_admin
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - PGDATA=/var/lib/postgresql/data/pgdata
    ports:
      - 5432:5432
    volumes:
      - postgres:/var/lib/postgresql/data
    restart: unless-stopped
  redis:
    image: redis
    container_name: redis
    ports:
      - 6379:6379
    volumes:
      - redis:/data

volumes:
  postgres:
  redis:
