services:
  calibre-web:
    image: lscr.io/linuxserver/calibre-web:latest
    container_name: calibre-web
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Amsterdam
      #- DOCKER_MODS=linuxserver/mods:universal-calibre #optional
      #- OAUTHLIB_RELAX_TOKEN_SCOPE=1 #optional
    volumes:
      - calibe_config:/config
      - nas_books:/books
    ports:
      - 8083:8083
    restart: unless-stopped

volumes:
  nas_books:
    external: true
    name: nas_books
  calibe_config: